<?php

/**
 * PluginKairanbanLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKairanbanLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginKairanbanLinkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginKairanbanLink');
    }
}