<?php

/**
 * PluginKairanbanReviewerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKairanbanReviewerTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginKairanbanReviewerTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('PluginKairanbanReviewer');
  }

  public function getKairanbanReviewrByKairanbanIdAndMemberId($kairanbanId, $memberId)
  {
    return Doctrine::getTable('KairanbanReviewer')->createQuery()
      ->where('kairanban_id = ?', $kairanbanId)
      ->andWhere('member_id = ?', $memberId)
      ->limit(1)
      ->fetchOne();
  }
}