<?php

/**
 * PluginKairanbanActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKairanbanActivityTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginKairanbanActivityTable
   */
  public static function getInstance()
  {
      return Doctrine_Core::getTable('PluginKairanbanActivity');
  }
}